version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    user: jenkins
    ports:
      - "${JENKINS_WEB_PORT:-8080}:8080"
      - "${JENKINS_AGENT_PORT:-50000}:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /etc/localtime:/etc/localtime:ro
    environment:
      - JENKINS_OPTS="--httpPort=8080"
    group_add:
      - "${DOCKER_GROUP_ID:-990}"  # Docker group ID
    networks:
      - jenkins-network
    restart: unless-stopped

volumes:
  jenkins_home:
    external: true
    name: jenkins_home  

networks:
  jenkins-network:
    name: jenkins-network
    driver: bridge
