version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    user: jenkins
    ports:
      - "${JENKINS_WEB_PORT:-8080}:8080"
      - "${JENKINS_AGENT_PORT:-50000}:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    environment:
      - JENKINS_OPTS="--httpPort=8080"
    group_add:
      - "${DOCKER_GROUP_ID:-990}"  # Docker group ID
    networks:
      - jenkins-network
    restart: unless-stopped

  jenkins-agent:
    image: jenkins/inbound-agent:latest
    container_name: jenkins-agent
    user: jenkins
    depends_on:
      - jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_agent_home:/home/jenkins/.jenkins
      - jenkins_agent_workspace:/home/jenkins/agent
    environment:
      - JENKINS_URL=${JENKINS_URL:-http://jenkins:8080}
      - JENKINS_AGENT_NAME=${JENKINS_AGENT_NAME:-FastAPI_App}
      - JENKINS_SECRET=${JENKINS_SECRET}
    group_add:
      - "${DOCKER_GROUP_ID:-990}"  # Docker group ID
    networks:
      - jenkins-network
    restart: unless-stopped

volumes:
  jenkins_home:
    driver: local
  jenkins_agent_home:
    driver: local
  jenkins_agent_workspace:
    driver: local

networks:
  jenkins-network:
    driver: bridge
