---
- name: Deploy FastAPI Application
  hosts: all
  become: yes
  vars:
    container_name: "fastapi-procmon"
    app_port: 8000
    
  tasks:
    - name: Pull Docker image
      shell: "docker pull {{ docker_image }}"
      
    - name: Stop existing container
      shell: "docker stop {{ container_name }} || true"
      
    - name: Remove existing container  
      shell: "docker rm {{ container_name }} || true"
      
    - name: Run new container
      shell: >
        docker run -d 
        --name {{ container_name }}
        --restart always
        -p {{ app_port }}:8000
        {{ docker_image }}
        
    - name: Wait for app to start
      wait_for:
        host: "{{ inventory_hostname }}"
        port: "{{ app_port }}"
        delay: 10
        timeout: 60
